//! ZEEX compiler — the build-time half.
//!
//! Templates are JSX, lowered by a script that runs inside the vendored QuickJS (`transform.js`), and the
//! IR it returns is turned into Zig source here. No Node, no npm, no Babel: the build already carries an
//! engine, and this is a script it runs.
//!
//! The generated function takes `props: anytype`, which is the whole trick: the template's `props.title`
//! becomes `props.title` in Zig, so a name the caller's struct does not have is a **compile error at the
//! call site**, not a blank spot on a page. Nothing about a template can fail at runtime for a reason a
//! compile could have caught, which is what makes this worth generating rather than interpreting.
//!
//! ```zig
//! const tasks = zeex.compile_template(allocator, @embedFile("tasks.jsx")) catch unreachable;
//! // written to zig-cache/zeex/tasks.zig and imported by the app
//! ```
//!
//! Escaping is the render tree's business, not the template's: `text` escapes and `raw` does not, so a
//! template never has to remember which interpolation was the safe one.

const std = @import("std");
const Script = @import("zscript").Script;

/// The transform, embedded so the compiler is self-contained: no path to find, no file to ship.
const transform_source = @embedFile("transform.js");

pub const Error = error{
    /// The template did not parse, or used something outside the subset. The detail says where.
    TemplateRejected,
    /// The transform returned something this compiler does not understand.
    MalformedIr,
    /// The engine could not be started or the script threw.
    TransformFailed,
    OutOfMemory,
};

/// Lower a JSX template to Zig source.
///
/// The result is a complete file: a `render(props: anytype, b: *Builder) !void` function, ready to be
/// imported. The caller owns it.
pub fn compile_template(allocator: std.mem.Allocator, template: []const u8) Error![:0]u8 {
    var script = Script.init() catch return error.TransformFailed;
    defer script.deinit();

    script.load("transform.js", transform_source, 1) catch return error.TemplateRejected;

    const ir_json = script.callText("transform", template, allocator) catch {
        // The script's own message for a rejected template is the useful part: a compiler that cannot say
        // which line it gave up on is not much of a compiler.
        std.debug.print("zeex: {s}\n", .{script.errorDetail()});

        return error.TemplateRejected;
    };
    defer allocator.free(ir_json);

    return generate(allocator, ir_json);
}

fn generate(allocator: std.mem.Allocator, ir_json: []const u8) Error![:0]u8 {
    const parsed = std.json.parseFromSlice(std.json.Value, allocator, ir_json, .{}) catch return error.MalformedIr;
    defer parsed.deinit();

    const root = parsed.value.object.get("ops") orelse return error.MalformedIr;
    if (root != .array) return error.MalformedIr;

    var out = std.Io.Writer.Allocating.init(allocator);
    errdefer out.deinit();
    const w = &out.writer;

    w.writeAll(
        \\//! Generated by zeex — do not edit.
        \\//!
        \\//! `props` is `anytype` on purpose: the template's names become field accesses here, so a name the
        \\//! caller's struct does not have fails to compile at the call site.
        \\
        \\const zurtr = @import("zurtr");
        \\
        \\pub fn render(props: anytype, b: *zurtr.live.tree.Builder) !void {
        \\
    ) catch return error.OutOfMemory;
    emitNodes(w, root.array.items, 1) catch return error.OutOfMemory;
    w.writeAll("}\n") catch return error.OutOfMemory;

    // A source file in Zig terms is sentinel-terminated: `std.zig.Ast.parse` takes it that way, and so
    // does anything that writes it to disk.
    const bytes = out.toOwnedSlice() catch return error.OutOfMemory;
    const terminated = allocator.realloc(bytes, bytes.len + 1) catch {
        allocator.free(bytes);

        return error.OutOfMemory;
    };
    terminated[bytes.len] = 0;

    return terminated[0..bytes.len :0];
}

fn indent(w: anytype, depth: usize) std.Io.Writer.Error!void {
    for (0..depth) |_| try w.writeAll("    ");
}

/// The emitter's error set, named because `emitNodes`/`emitNode` are mutually recursive and Zig cannot
/// infer an error set through a cycle.
const EmitError = std.Io.Writer.Error || error{MalformedIr};

fn emitNodes(w: anytype, nodes: []const std.json.Value, depth: usize) EmitError!void {
    for (nodes) |node| try emitNode(w, node, depth);
}

fn emitNode(w: anytype, node: std.json.Value, depth: usize) EmitError!void {
    const object = node.object;
    const op = object.get("op") orelse return error.MalformedIr;
    const name = op.string;

    if (std.mem.eql(u8, name, "text")) {
        const value = object.get("value").?.string;
        try indent(w, depth);
        try w.print("try b.text(\"{f}\");\n", .{std.zig.fmtString(value)});

        return;
    }

    if (std.mem.eql(u8, name, "expr")) {
        try indent(w, depth);
        try w.writeAll("try b.text(");
        try pathText(w, object.get("path").?);
        try w.writeAll(");\n");

        return;
    }

    if (std.mem.eql(u8, name, "raw")) {
        try indent(w, depth);
        try w.writeAll("try b.raw(");
        try pathText(w, object.get("path").?);
        try w.writeAll(");\n");

        return;
    }

    if (std.mem.eql(u8, name, "if")) {
        // The transform emits `otherwise` empty; a non-empty one is an `else` this emitter does not
        // support, and ignoring it would silently drop a branch. Refuse it as itself, loudly, rather
        // than let a future producer's branch disappear.
        if (object.get("otherwise")) |otherwise| {
            const empty = switch (otherwise) {
                .array => |items| items.items.len == 0,
                else => false,
            };
            if (!empty) {
                std.debug.print("zeex: the IR's `if` carries an `otherwise` branch, which this emitter does not support\n", .{});

                return error.MalformedIr;
            }
        }

        try indent(w, depth);
        try w.writeAll("if (");
        try pathText(w, object.get("path").?);
        try w.writeAll(") {\n");
        try emitNodes(w, object.get("then").?.array.items, depth + 1);
        try indent(w, depth);
        try w.writeAll("}\n");
        return;
    }

    if (std.mem.eql(u8, name, "for")) {
        const item = object.get("item").?.string;
        try indent(w, depth);
        try w.writeAll("for (");
        try pathText(w, object.get("path").?);
        try w.print(") |{s}| {{\n", .{item});
        try emitNodes(w, object.get("body").?.array.items, depth + 1);
        try indent(w, depth);
        try w.writeAll("}\n");

        return;
    }

    if (std.mem.eql(u8, name, "element")) {
        const tag = object.get("tag").?.string;

        // A capitalised tag is a component call: the props struct carries the component, and the
        // attributes become its argument struct — the JSX convention, lowered rather than interpreted.
        if (tag.len > 0 and std.ascii.isUpper(tag[0])) {
            // A component takes no children (the convention for passing them is not decided), and the
            // transform refuses them, so an IR that still carries some is not one this emitter knows:
            // say so rather than dropping them.
            const component_children = if (object.get("children")) |children| switch (children) {
                .array => |items| items.items.len != 0,
                else => true,
            } else false;
            if (component_children) {
                std.debug.print("zeex: <{s}> is a component and the IR carries children; this emitter has nowhere to put them\n", .{tag});

                return error.MalformedIr;
            }

            try indent(w, depth);
            try w.print("try props.{s}(.{{", .{tag});
            if (object.get("attrs")) |attrs| {
                for (attrs.array.items, 0..) |attr, index| {
                    const attr_name = attr.object.get("name").?.string;
                    const value = attr.object.get("value").?;
                    if (index > 0) try w.writeAll(", ");
                    try w.print(".{s} = ", .{attr_name});
                    try emitAttrValue(w, value);
                }
            }
            try w.writeAll("}, b);\n");

            return;
        }

        try indent(w, depth);
        try w.print("try b.element(\"{f}\", &.{{", .{std.zig.fmtString(tag)});
        if (object.get("attrs")) |attrs| {
            for (attrs.array.items, 0..) |attr, index| {
                const attr_name = attr.object.get("name").?.string;
                const value = attr.object.get("value").?;
                const kind = value.object.get("kind").?.string;

                if (index > 0) try w.writeAll(", ");
                if (std.mem.eql(u8, kind, "static")) {
                    try w.print(".{{ .name = \"{f}\", .value = \"{f}\" }}", .{
                        std.zig.fmtString(attr_name),
                        std.zig.fmtString(value.object.get("value").?.string),
                    });
                } else if (std.mem.eql(u8, kind, "toggle")) {
                    // A bare attribute is present: an empty value is true for an HTML boolean
                    // attribute, and `AttrSpec.value == null` would omit the attribute instead.
                    try w.print(".{{ .name = \"{f}\", .value = \"\" }}", .{std.zig.fmtString(attr_name)});
                } else if (std.mem.eql(u8, kind, "path")) {
                    try w.print(".{{ .name = \"{f}\", .value = ", .{std.zig.fmtString(attr_name)});
                    try pathText(w, value.object.get("path").?);
                    try w.writeAll(" }");
                } else {
                    return error.MalformedIr;
                }
            }
        }
        try w.writeAll("}, 0);\n");

        try emitNodes(w, object.get("children").?.array.items, depth + 1);

        try indent(w, depth);
        try w.writeAll("try b.close();\n");

        return;
    }

    return error.MalformedIr;
}

/// Write the Zig expression for an attribute value: a path, a bare attribute (present, written as an
/// empty string), or a static string in the component form.
fn emitAttrValue(w: anytype, value: std.json.Value) EmitError!void {
    const kind = value.object.get("kind").?.string;

    if (std.mem.eql(u8, kind, "path")) {
        return pathText(w, value.object.get("path").?);
    }

    if (std.mem.eql(u8, kind, "static")) {
        return w.print("\"{f}\"", .{std.zig.fmtString(value.object.get("value").?.string)});
    }

    if (std.mem.eql(u8, kind, "toggle")) {
        return w.writeAll("\"\"");
    }

    return error.MalformedIr;
}

/// Write the Zig expression a path denotes: `["title"]` is `props.title`, `["$tag"]` is the loop variable
/// `tag`. The two forms are distinct in the IR so a loop variable can never be mistaken for a property.
fn pathText(w: anytype, path: std.json.Value) EmitError!void {
    if (path != .array or path.array.items.len == 0) return error.MalformedIr;

    // A loop variable is an identifier the enclosing `for` binds; anything else is a field of props. The
    // decision is made on the first segment, because writing `props.` first is not recoverable.
    const head = path.array.items[0].string;
    if (head.len > 0 and head[0] == '$') {
        if (path.array.items.len != 1) return error.MalformedIr;

        return w.print("{s}", .{head[1..]});
    }

    try w.writeAll("props");
    for (path.array.items) |segment| try w.print(".{s}", .{segment.string});
}

test "a template lowers to Zig that parses, and the IR says what it should" {
    const allocator = std.testing.allocator;

    const source =
        \\<div class="card">
        \\  <h1>{props.title}</h1>
        \\  {props.show && <p>{props.body}</p>}
        \\  <ul>{props.tags.map(function (tag) { return <li>{tag}</li>; })}</ul>
        \\  {__raw(props.trusted)}
        \\</div>
    ;

    const generated = try compile_template(allocator, source);
    defer allocator.free(generated);

    // The generated file must be valid Zig, which is the only thing that stops codegen bugs from
    // becoming a confusing error in a user's build. `std.zig.Ast` is the compiler's own parser.
    var ast = try std.zig.Ast.parse(allocator, generated, .{ .mode = .zig });
    defer ast.deinit(allocator);

    // A codegen bug that only says "4 parse errors" is useless to whoever hits it, so say what was
    // generated and where the parser gave up. That is the whole diagnostic.
    if (ast.errors.len != 0) {
        std.debug.print("zeex: generated source does not parse:\n{s}\n", .{generated});
        for (ast.errors) |err| std.debug.print("  parse error at token {d}\n", .{err.token});
    }

    try std.testing.expectEqual(@as(usize, 0), ast.errors.len);
}

test "a bare attribute lowers to a present attribute with an empty value" {
    const allocator = std.testing.allocator;

    // A bare attribute is present, which for an HTML boolean attribute means an empty value. The
    // emitter used to have no case for the transform's `toggle` kind at all, so this template failed
    // with MalformedIr and no line; the pair is what this test holds together.
    const generated = try compile_template(allocator, "<input disabled>");
    defer allocator.free(generated);

    try std.testing.expect(std.mem.indexOf(u8, generated, ".name = \"disabled\", .value = \"\"") != null);

    var ast = try std.zig.Ast.parse(allocator, generated, .{ .mode = .zig });
    defer ast.deinit(allocator);
    try std.testing.expectEqual(@as(usize, 0), ast.errors.len);
}

test "what the subset refuses comes back as TemplateRejected, with the line" {
    const allocator = std.testing.allocator;

    // Children on a component: there is no decided convention for passing them, and dropping them
    // silently is worse than refusing.
    try std.testing.expectError(error.TemplateRejected, compile_template(allocator,
        \\<div>
        \\  <Card>
        \\    <p>child</p>
        \\  </Card>
        \\</div>
    ));

    // An expression after `props.`: a path segment is a field name, and the emitter writes it into the
    // generated source verbatim, so `props.a + 1` would become code rather than a compile error here.
    try std.testing.expectError(error.TemplateRejected, compile_template(allocator, "<div>{props.a + 1}</div>"));

    // A loop variable named `b` would shadow the Builder inside the generated function.
    try std.testing.expectError(error.TemplateRejected, compile_template(allocator, "<ul>{props.items.map(b => <li>{b}</li>)}</ul>"));
}
