//! ZEEX compiler — the build-time half.
//!
//! Templates are JSX, lowered by a script that runs inside the vendored QuickJS (`transform.js`), and the
//! IR it returns is turned into Zig source here. No Node, no npm, no Babel: the build already carries an
//! engine, and this is a script it runs.
//!
//! The generated function takes `props: anytype`, which is the whole trick: the template's `props.title`
//! becomes `props.title` in Zig, so a name the caller's struct does not have is a **compile error at the
//! call site**, not a blank spot on a page. Nothing about a template can fail at runtime for a reason a
//! compile could have caught, which is what makes this worth generating rather than interpreting.
//!
//! ```zig
//! const tasks = zeex.compile_template(allocator, @embedFile("tasks.jsx")) catch unreachable;
//! // written to zig-cache/zeex/tasks.zig and imported by the app
//! ```
//!
//! Escaping is the render tree's business, not the template's: `text` escapes and `raw` does not, so a
//! template never has to remember which interpolation was the safe one.

const std = @import("std");
const Script = @import("../script/root.zig").Script;

/// The transform, embedded so the compiler is self-contained: no path to find, no file to ship.
const transform_source = @embedFile("transform.js");

pub const Error = error{
    /// The template did not parse, or used something outside the subset. The detail says where.
    TemplateRejected,
    /// The transform returned something this compiler does not understand.
    MalformedIr,
    /// The engine could not be started or the script threw.
    TransformFailed,
    OutOfMemory,
};

/// Lower a JSX template to Zig source.
///
/// The result is a complete file: a `render(props: anytype, b: *Builder) !void` function, ready to be
/// imported. The caller owns it.
pub fn compile_template(allocator: std.mem.Allocator, template: []const u8) Error![:0]u8 {
    var script = Script.init() catch return error.TransformFailed;
    defer script.deinit();

    script.load("transform.js", transform_source, 1) catch return error.TemplateRejected;

    const ir_json = script.callText("transform", template, allocator) catch {
        // The script's own message for a rejected template is the useful part.
        return error.TemplateRejected;
    };
    defer allocator.free(ir_json);

    return generate(allocator, ir_json);
}

fn generate(allocator: std.mem.Allocator, ir_json: []const u8) Error![:0]u8 {
    const parsed = std.json.parseFromSlice(std.json.Value, allocator, ir_json, .{}) catch return error.MalformedIr;
    defer parsed.deinit();

    const root = parsed.value.object.get("ops") orelse return error.MalformedIr;
    if (root != .array) return error.MalformedIr;

    var out = std.Io.Writer.Allocating.init(allocator);
    errdefer out.deinit();
    const w = &out.writer;

    w.writeAll(
        \\//! Generated by zeex — do not edit.
        \\//!
        \\//! `props` is `anytype` on purpose: the template's names become field accesses here, so a name the
        \\//! caller's struct does not have fails to compile at the call site.
        \\
        \\const zurtr = @import("zurtr");
        \\
        \\pub fn render(props: anytype, b: *zurtr.live.tree.Builder) !void {
        \\
    ) catch return error.OutOfMemory;
    emitNodes(w, root.array.items, 1) catch return error.OutOfMemory;
    w.writeAll("}\n") catch return error.OutOfMemory;

    // A source file in Zig terms is sentinel-terminated: `std.zig.Ast.parse` takes it that way, and so
    // does anything that writes it to disk.
    const bytes = out.toOwnedSlice() catch return error.OutOfMemory;
    const terminated = allocator.realloc(bytes, bytes.len + 1) catch {
        allocator.free(bytes);

        return error.OutOfMemory;
    };
    terminated[bytes.len] = 0;

    return terminated[0..bytes.len :0];
}

fn indent(w: anytype, depth: usize) !void {
    for (0..depth) |_| try w.writeAll("    ");
}

fn emitNodes(w: anytype, nodes: []const std.json.Value, depth: usize) !void {
    for (nodes) |node| try emitNode(w, node, depth);
}

fn emitNode(w: anytype, node: std.json.Value, depth: usize) !void {
    const object = node.object;
    const op = object.get("op") orelse return error.MalformedIr;
    const name = op.string;

    if (std.mem.eql(u8, name, "text")) {
        const value = object.get("value").?.string;
        try indent(w, depth);
        try w.print("try b.text({f});\n", .{std.zig.fmtString(value)});

        return;
    }

    if (std.mem.eql(u8, name, "expr")) {
        try indent(w, depth);
        try w.writeAll("try b.text(");
        try pathText(w, object.get("path").?);
        try w.writeAll(");\n");

        return;
    }

    if (std.mem.eql(u8, name, "raw")) {
        try indent(w, depth);
        try w.writeAll("try b.raw(");
        try pathText(w, object.get("path").?);
        try w.writeAll(");\n");

        return;
    }

    if (std.mem.eql(u8, name, "if")) {
        try indent(w, depth);
        try w.writeAll("if (");
        try pathText(w, object.get("path").?);
        try w.writeAll(") {\n");
        try emitNodes(w, object.get("then").?.array.items, depth + 1);
        try indent(w, depth);
        try w.writeAll("}\n");
        return;
    }

    if (std.mem.eql(u8, name, "for")) {
        const item = object.get("item").?.string;
        try indent(w, depth);
        try w.writeAll("for (");
        try pathText(w, object.get("path").?);
        try w.print(") |{s}| {{\n", .{item});
        try emitNodes(w, object.get("body").?.array.items, depth + 1);
        try indent(w, depth);
        try w.writeAll("}\n");

        return;
    }

    if (std.mem.eql(u8, name, "element")) {
        const tag = object.get("tag").?.string;

        // A capitalised tag is a component call: the props struct carries the component, and the
        // attributes become its argument struct — the JSX convention, lowered rather than interpreted.
        if (tag.len > 0 and std.ascii.isUpper(tag[0])) {
            try indent(w, depth);
            try w.print("try props.{s}(.{", .{tag});
            if (object.get("attrs")) |attrs| {
                for (attrs.array.items, 0..) |attr, index| {
                    const attr_name = attr.object.get("name").?.string;
                    const value = attr.object.get("value").?;
                    if (index > 0) try w.writeAll(", ");
                    try w.print(".{s} = ", .{attr_name});
                    try emitAttrValue(w, value);
                }
            }
            try w.writeAll("}, b);\n");

            return;
        }

        try indent(w, depth);
        try w.print("try b.element({f}, &.{{", .{std.zig.fmtString(tag)});
        if (object.get("attrs")) |attrs| {
            for (attrs.array.items, 0..) |attr, index| {
                const attr_name = attr.object.get("name").?.string;
                const value = attr.object.get("value").?;
                const kind = value.object.get("kind").?.string;

                if (index > 0) try w.writeAll(", ");
                if (std.mem.eql(u8, kind, "static")) {
                    try w.print(".{{ .name = {f}, .value = {f} }}", .{
                        std.zig.fmtString(attr_name),
                        std.zig.fmtString(value.object.get("value").?.string),
                    });
                } else if (std.mem.eql(u8, kind, "path")) {
                    try w.print(".{{ .name = {f}, .value = {s} }}", .{
                        std.zig.fmtString(attr_name),
                        pathText(value.object.get("path").?),
                    });
                } else {
                    return error.MalformedIr;
                }
            }
        }
        try w.writeAll("}, 0);\n");

        try emitNodes(w, object.get("children").?.array.items, depth + 1);

        try indent(w, depth);
        try w.writeAll("try b.close();\n");

        return;
    }

    return error.MalformedIr;
}

/// Write the Zig expression for an attribute value: a path, a toggle, or the component form's value.
fn emitAttrValue(w: anytype, value: std.json.Value) !void {
    const kind = value.object.get("kind").?.string;

    if (std.mem.eql(u8, kind, "path")) {
        return pathText(w, value.object.get("path").?);
    }

    if (std.mem.eql(u8, kind, "static")) {
        return w.print("{f}", .{std.zig.fmtString(value.object.get("value").?.string)});
    }

    return error.MalformedIr;
}

/// Write the Zig expression a path denotes: `["title"]` is `props.title`, `["$tag"]` is the loop variable
/// `tag`. The two forms are distinct in the IR so a loop variable can never be mistaken for a property.
fn pathText(w: anytype, path: std.json.Value) !void {
    if (path != .array or path.array.items.len == 0) return error.MalformedIr;

    try w.writeAll("props");
    for (path.array.items) |segment| {
        const name = segment.string;
        if (name.len > 0 and name[0] == '$') {
            // A loop variable, bound by the enclosing `for`'s capture.
            if (path.array.items.len != 1) return error.MalformedIr;

            return w.print("{s}", .{name[1..]});
        }

        try w.print(".{s}", .{name});
    }
}

test "a template lowers to Zig that parses, and the IR says what it should" {
    const allocator = std.testing.allocator;

    const source =
        \\<div class="card">
        \\  <h1>{props.title}</h1>
        \\  {props.show && <p>{props.body}</p>}
        \\  <ul>{props.tags.map(function (tag) { return <li>{tag}</li>; })}</ul>
        \\  {__raw(props.trusted)}
        \\</div>
    ;

    const generated = try compile_template(allocator, source);
    defer allocator.free(generated);

    // The generated file must be valid Zig, which is the only thing that stops codegen bugs from
    // becoming a confusing error in a user's build. `std.zig.Ast` is the compiler's own parser.
    var ast = try std.zig.Ast.parse(allocator, generated, .zig);
    defer ast.deinit(allocator);

    try std.testing.expectEqual(@as(usize, 0), ast.errors.len);
}
